namespace SpriteKind {
    export const Gas = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    while (controller.A.isPressed()) {
        projectile = sprites.createProjectileFromSprite(img`
            ........f........
            .......f4f.......
            ......f242f......
            ......fffff......
            ......f919f......
            ......f919f......
            ......f919f......
            ......f919f......
            ......f919f......
            .....f99199f.....
            ....fff919fff....
            ......f919f......
            .......fff.......
            ......24542......
            ......24542......
            .......252.......
            ........2........
            .................
            `, mySprite, 0, -100)
        projectile.startEffect(effects.spray)
        pause(350)
    }
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function (sprite, otherSprite) {
    sprite.destroy(effects.disintegrate, 500)
    otherSprite.destroy(effects.fire, 500)
    info.changeScoreBy(1000)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Gas, function (sprite, otherSprite) {
    statusbar.value = 100
    otherSprite.destroy()
})
statusbars.onZero(StatusBarKind.Energy, function (status) {
    game.over(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    otherSprite.destroy(effects.disintegrate, 200)
})
let myEnemy: Sprite = null
let myFuel: Sprite = null
let projectile: Sprite = null
let statusbar: StatusBarSprite = null
let mySprite: Sprite = null
effects.starField.startScreenEffect()
mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . 8 8 . . . . . . . 
    . . . . . . 8 8 8 8 . . . . . . 
    . . . . . 8 8 8 8 8 8 . . . . . 
    . . . . 8 8 f f f f 8 8 . . . . 
    . . . 8 8 8 f 1 1 f 8 8 8 . . . 
    . . 8 8 8 8 f 1 1 f 8 8 8 8 . . 
    8 8 8 8 8 8 f f f f 8 8 8 8 8 8 
    8 . 8 8 8 8 8 8 8 8 8 8 8 8 . 8 
    8 . 8 f f f f 1 1 f f f f 8 . 8 
    8 . 8 f 4 4 f f f f 4 4 f 8 . 8 
    8 . 8 f 4 4 f 1 1 f 4 4 f 8 . 8 
    8 . 8 f 4 4 f f f f 4 4 f 8 . 8 
    8 . 8 f 4 4 f 1 1 f 4 4 f 8 . 8 
    8 . . f 4 4 f f f f 4 4 f 8 . 8 
    8 . . . 2 2 . . . . 2 2 . . . 8 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
mySprite.setStayInScreen(true)
statusbar = statusbars.create(20, 4, StatusBarKind.Energy)
statusbar.attachToSprite(mySprite, -23, 0)
info.setScore(0)
info.setLife(3)
game.onUpdateInterval(5000, function () {
    myFuel = sprites.createProjectileFromSide(img`
        . . . f f f f . . . 
        . . f 5 5 5 5 f . . 
        . f 5 1 5 5 5 5 f . 
        f 5 1 5 2 5 5 5 4 f 
        f 5 1 5 5 5 5 5 4 f 
        f 5 5 5 5 2 5 5 4 f 
        f 5 5 5 5 5 5 5 4 f 
        . f 5 5 5 5 5 4 f . 
        . . f 4 4 4 4 f . . 
        . . . f f f f . . . 
        `, 0, 50)
    myFuel.x = randint(5, 155)
    myFuel.setKind(SpriteKind.Gas)
})
game.onUpdateInterval(1000, function () {
    myEnemy = sprites.createProjectileFromSide(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, 0, 50)
    myEnemy.x = randint(5, 155)
    myEnemy.setKind(SpriteKind.Enemy)
})
game.onUpdateInterval(300, function () {
    statusbar.value += -1
})
